# Form implementation generated from reading ui file 'dicts_setting.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(348, 300)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddFolder = QPushButton(Dialog)
        self.btnAddFolder.setObjectName("btnAddFolder")
        self.horizontalLayout.addWidget(self.btnAddFolder)
        self.btnRemoveFolder = QPushButton(Dialog)
        self.btnRemoveFolder.setObjectName("btnRemoveFolder")
        self.horizontalLayout.addWidget(self.btnRemoveFolder)
        spacerItem = QSpacerItem(
            40,
            20,
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidgetFolders = QListWidget(Dialog)
        self.listWidgetFolders.setObjectName("listWidgetFolders")
        self.verticalLayout.addWidget(self.listWidgetFolders)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkUseFilename = QCheckBox(Dialog)
        self.checkUseFilename.setObjectName("checkUseFilename")
        self.horizontalLayout_2.addWidget(self.checkUseFilename)
        self.checkExportMedia = QCheckBox(Dialog)
        self.checkExportMedia.setObjectName("checkExportMedia")
        self.horizontalLayout_2.addWidget(self.checkExportMedia)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QDialogButtonBox.StandardButton.Cancel | QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        self.btnAddFolder.clicked.connect(Dialog.add_folder)  # type: ignore
        self.btnRemoveFolder.clicked.connect(Dialog.remove_folder)  # type: ignore
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dicts Setting"))
        self.btnAddFolder.setText(_translate("Dialog", "Add Folder"))
        self.btnRemoveFolder.setText(_translate("Dialog", "Remove Folder"))
        self.checkUseFilename.setText(
            _translate("Dialog", "Use filename as dict label")
        )
        self.checkExportMedia.setText(_translate("Dialog", "Export media files"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
