# Form implementation generated from reading ui file 'dict_chooser.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(341, 34)
        self.horizontalLayout = QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(6, 5, 6, 5)
        self.horizontalLayout.setSpacing(18)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCheckWord = QRadioButton(Form)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCheckWord.sizePolicy().hasHeightForWidth())
        self.btnCheckWord.setSizePolicy(sizePolicy)
        self.btnCheckWord.setMinimumSize(QSize(100, 0))
        self.btnCheckWord.setMaximumSize(QSize(100, 16777215))
        self.btnCheckWord.setObjectName("btnCheckWord")
        self.horizontalLayout.addWidget(self.btnCheckWord)
        self.comboDicts = QComboBox(Form)
        self.comboDicts.setObjectName("comboDicts")
        self.horizontalLayout.addWidget(self.comboDicts)
        self.comboDictFields = QComboBox(Form)
        self.comboDictFields.setObjectName("comboDictFields")
        self.horizontalLayout.addWidget(self.comboDictFields)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnCheckWord.setText(_translate("Form", "Word field"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
