# Form implementation generated from reading ui file 'options.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from aqt.qt import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(525, 412)
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Preferred,
            QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnDictChooser = QPushButton(Dialog)
        self.btnDictChooser.setObjectName("btnDictChooser")
        self.horizontalLayout_2.addWidget(self.btnDictChooser)
        self.btnModelChooser = QPushButton(Dialog)
        self.btnModelChooser.setObjectName("btnModelChooser")
        self.horizontalLayout_2.addWidget(self.btnModelChooser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lwDicts = QListWidget(Dialog)
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lwDicts.sizePolicy().hasHeightForWidth())
        self.lwDicts.setSizePolicy(sizePolicy)
        self.lwDicts.setMaximumSize(QSize(16777215, 16777215))
        self.lwDicts.setObjectName("lwDicts")
        self.verticalLayout.addWidget(self.lwDicts)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAbout = QPushButton(Dialog)
        self.btnAbout.setObjectName("btnAbout")
        self.horizontalLayout.addWidget(self.btnAbout)
        spacerItem = QSpacerItem(
            40,
            20,
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.lwDicts.setCurrentRow(-1)
        self.btnDictChooser.clicked.connect(Dialog.show_dictSetting_dlg)  # type: ignore
        self.btnModelChooser.clicked.connect(Dialog.show_models)  # type: ignore
        self.buttonBox.accepted.connect(Dialog.save)  # type: ignore
        self.btnAbout.clicked.connect(Dialog.show_about)  # type: ignore
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.btnDictChooser.setText(_translate("Dialog", "Dict folders"))
        self.btnModelChooser.setText(_translate("Dialog", "Choose note types"))
        self.btnAbout.setText(_translate("Dialog", "About"))


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
